(ns vygga.test-runner
  (:require
   [cljs.test :refer-macros [run-tests]]
   [vygga.crypto-test]
   [vygga.core-test]
   [vygga.yggstack-test]
   [vygga.events.theme-test]
   [vygga.events.navigation-test]
   [vygga.events.app-test]
   [vygga.events.yggstack-test]
   [vygga.events.messenger-test]
   [vygga.events.voip-test]
   [vygga.events.debug-test]
   [vygga.subs-test]
   [vygga.view.yggstatus-test]
   [vygga.view.settings-test]
   [vygga.view.contacts-test]
   [vygga.view.chat-test]
   [vygga.view.navigation-test]
   [vygga.view.calls-test]
   [vygga.view.debug-test]
   [vygga.widgets-test]
   [vygga.storage-test]
   [vygga.messenger-test]
   [vygga.tcp-server-test]
   [vygga.tcp-client-test]
   [vygga.audio-server-test]
   [vygga.voip-connection-test]))

(defn -main [& _]
  (run-tests
   'vygga.crypto-test
   'vygga.core-test
   'vygga.yggstack-test
   'vygga.events.theme-test
   'vygga.events.navigation-test
   'vygga.events.app-test
   'vygga.events.yggstack-test
   'vygga.events.messenger-test
   'vygga.events.voip-test
   'vygga.events.debug-test
   'vygga.subs-test
   'vygga.view.yggstatus-test
   'vygga.view.settings-test
   'vygga.view.contacts-test
   'vygga.view.chat-test
   'vygga.view.navigation-test
   'vygga.view.calls-test
   'vygga.view.debug-test
   'vygga.widgets-test
   'vygga.storage-test
   'vygga.messenger-test
   'vygga.tcp-server-test
   'vygga.tcp-client-test
   'vygga.audio-server-test
   'vygga.voip-connection-test))
